const FETCH_POST = 'FETCH_POST';
const FETCH_POST_SUCCEED = 'FETCH_POST_SUCCEED';
const FETCH_POST_FAIL = 'FETCH_POST_FAIL';
const CREATE_POST = 'CREATE_POST';
const CREATE_POST_SUCCEED = 'CREATE_POST_SUCCEED';
const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export { 
  FETCH_POST, 
  FETCH_POST_SUCCEED,
  FETCH_POST_FAIL,
  CREATE_POST,
  CREATE_POST_SUCCEED,
  CREATE_POST_FAIL
};